### ISSUE TITLE
Crash loading scene from scripting

### ISSUE THREAD

**Issue by Acaree** [JellyBitStudios/JellyBitEngine#80]
* Description: Crash loading scene from scripting

* Build: 0.3.3.4

* Type: Scripting/resources

* Steps to reproduce: Next lines in any script update: 

 if (Input.GetKeyDown(KeyCode.KEY_M))
        {
            SceneManager.LoadScene("main scene");
        }

Execute game in engine and press M

* Frequency: Always

**Comment by Acaree** [comment]
https://drive.google.com/open?id=1-aG_3XCrufXIPPOebtOr1aTugRlZ-7Be

**Comment by Jony635** [comment]
We need to update to a more recent engine build. 
Also, in the latest version the Main Scene crashes because of it is apparently corrupted (UI has changed the save and load), and with other fixed scenes the Quadtree enters in an infinit loop. I reference the bug below.

[Issue 81](https://github.com/JellyBitStudios/JellyBitEngine/issues/81)

**Comment by Jony635** [comment]
Fixed, but now we detected crashes in Physics when loading scenes during play mode.
Here I reference the @Sandruski issue.
https://github.com/JellyBitStudios/JellyBitEngine/issues/82
